# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b9cb09ad08d7ad0a42fd3e3fe6988cb1ecfa387a67727c3c7c9ce4e9a6a7ff88e184c589ad014ca19e09ce92dac95adebf8834ba4164b3184db99f640e9aa4

test:
  secret_key_base: 3b191b93fe74e16b752fe124f0ab5db9707d743da1d32800178438ea49c653f0bedd8bd1df7ad51514dce6c6ff7d20cb2fb74d26d3ab19b1881edb79ce5ef810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
